Feature/prf to zn
cryptimeleon/craco pull request #56
Opened 2021-03-31 12:29 UTC by this-kramer

**Changes:**
 - Add `LongAesPrf` that uses k keys for a PRF n*kn->kn
 - Add `HashThenPrfToZn` for retrieving Zn elements from a PRF
 - Bugfix of `ByteArrayImplementation.append`

2021-04-06 17:07 UTC, JanBobolz reviewed
My commit broke the tests, but I don't see how anything should have changed semantically. I guess previously, your copyOfRange appended zeros to keys?! Not sure what's going on :)

2021-04-06 17:10 UTC, this-kramer commented on src/main/java/org/cryptimeleon/craco/prf/zn/LongAesPseudoRandomFunction.java
> +        for (int i = 0; i <= factor; i++) {
```suggestion
        for (int i = 0; i < factor; i++) {
```
I think that's a good point

2021-04-06 17:14 UTC, this-kramer commented
> My commit broke the tests, but I don't see how anything should have changed semantically. I guess previously, your copyOfRange appended zeros to keys?! Not sure what's going on :)

Yes, I guess the copyOfRange function breaks it. It was more of a appendBytes :)

2021-04-09 12:27 UTC, pschuermann97 approved these changes
The shorthand for creating multiple pseudorandom elements would be great. Otherwise, it looks fine to me.

2021-04-09 12:27 UTC, pschuermann97 commented on src/main/java/org/cryptimeleon/craco/prf/zn/HashThenPrfToZn.java
> +}
How about a shorthand method for generating multiple pseudorandom ring elements at once?
The Issue<->Join protocol of the cryptimeleon incentive system e.g. needs 6 of them

2021-04-09 12:27 UTC, pschuermann97 commented on src/main/java/org/cryptimeleon/craco/prf/zn/LongAesPseudoRandomFunction.java
> +        }
Adding a this in front of object variables would make this code easier to read imo.
But maybe this is just me :)

2021-04-09 12:31 UTC, this-kramer commented on src/main/java/org/cryptimeleon/craco/prf/zn/HashThenPrfToZn.java
> +        if (hashFunction.getOutputLength() * 8 < aesKeyLength) {
Yes

2021-04-09 12:34 UTC, this-kramer commented on src/main/java/org/cryptimeleon/craco/prf/zn/HashThenPrfToZn.java
> +}
That's a good point! I think I will add a function for Vector<ZnElement> for some vector size input.

2021-04-09 12:35 UTC, this-kramer commented on src/main/java/org/cryptimeleon/craco/prf/zn/LongAesPseudoRandomFunction.java
> +        }
Which object variable do you mean?

2021-04-09 13:36 UTC, this-kramer commented
Added proposals A and B for hashThenPrfToZnVector:
A adds a counter prefix to the hash input.
B runs hashThenPrfToZnVector with the input and then uses the output ZnElement as the next input. 

Some timings are below

2021-04-09 13:40 UTC, this-kramer commented on src/main/java/org/cryptimeleon/craco/prf/zn/HashThenPrfToZn.java
> +}
See my [comment](https://github.com/cryptimeleon/craco/pull/56#issuecomment-816687159)

2021-04-11 14:57 UTC, JanBobolz commented
I guess B would not formally be considered a PRF anymore, since querying (y_1, y_2, ...)  = F(x) and then querying F(y_1) will yield (y_2, ...), which makes it easily distinguishable from a random function. 

It may be that your version A is just slower right now because you're hashing twice. Once via the `SHAHashAccumulator` and then within the `hashThenPrfToZn()` call. If you replace the `SHAHashAccumulator` with just a normal `ByteArrayAccumulator` (or whatever it's called), I think most of the performance difference should vanish. 
Also note that version A is easily parallelizeable, so that would certainly be my go-to.

Version A is secure. However, currently, it's iffy to use both `hashThenPrfToZn` and `hashThenPrfToZnVectorA` because their results will correlate. Maybe prepend something to the input of the hash function - like the number of elements you're deriving from this call (`vectorSize` or `1`) to unentangle this.

2021-04-11 15:33 UTC, JanBobolz commented on src/main/java/org/cryptimeleon/craco/prf/zn/HashThenPrfToZn.java
> +                (p.bitLength() + aesKeyLength + OVERSUBSCRIPTION + 1) / aesKeyLength  // Compute number of AES instances required to get desired output bit length
I feel like this is probably not enough, no? Let's say aesKeyLength = 128, p = 2^123, p.bitLength = 124. Then the number of AES instances set up here is 1. However for the divideAndRemainder below, (2^128-1) = 2^4 * 2^123 + (2^128 - 1 - 2^127).
So the good interval has size 2^127. The full interval has size 2^128. So the chances of landing in the good interval are 1/2 ?!

Just for my own sanity, let's say, you set up two AES instances for aesKeyLength = 128, p = 2^123.
Then (2^256-1) = 2^132 * 2^123 + (2^256 - 1 - 2^255). So the good interval has size 2^255. The full interval has size 2^256. So again landing in the good interval turns out to happen with probability 1/2 ?!

Where is my error?

2021-04-11 15:42 UTC, this-kramer commented
> I guess B would not formally be considered a PRF anymore, since querying (y_1, y_2, ...) = F(x) and then querying F(y_1) will yield (y_2, ...), which makes it easily distinguishable from a random function.
> 
> It may be that your version A is just slower right now because you're hashing twice. Once via the `SHAHashAccumulator` and then within the `hashThenPrfToZn()` call. If you replace the `SHAHashAccumulator` with just a normal `ByteArrayAccumulator` (or whatever it's called), I think most of the performance difference should vanish.
> Also note that version A is easily parallelizeable, so that would certainly be my go-to.
> 
> Version A is secure. However, currently, it's iffy to use both `hashThenPrfToZn` and `hashThenPrfToZnVectorA` because their results will correlate. Maybe prepend something to the input of the hash function - like the number of elements you're deriving from this call (`vectorSize` or `1`) to untangle this.

Good point, I just realized that the SHAHashAccumulator does not prepare using SHA, but actually uses SHA to generate the byte[]. I will adapt that and then use version A

2021-04-11 15:48 UTC, this-kramer commented on src/main/java/org/cryptimeleon/craco/prf/zn/HashThenPrfToZn.java
> +                (p.bitLength() + aesKeyLength + OVERSUBSCRIPTION + 1) / aesKeyLength  // Compute number of AES instances required to get desired output bit length
I think you're leaving out the OVERSUBSCRIPTION (e.g. 128) which will then cause having two instances and a much higher success probability.
For example, AES128, p~123bit, OVERSUBSCRIPTION with 128 bits yields `(128+123+128+1)/128=2` instances of aes, hence having a good interval of size ~ 2^255 and a bad interval of < 2^123 bits each. Hence, the probability of landing in the bad interval should be bound by `(1/2)^OVERSUBSCRIPTION`.

Or did I miss something

2021-04-13 08:19 UTC, this-kramer commented on src/main/java/org/cryptimeleon/craco/prf/zn/HashThenPrfToZn.java
> +                (p.bitLength() + aesKeyLength + OVERSUBSCRIPTION + 1) / aesKeyLength  // Compute number of AES instances required to get desired output bit length
Edit: For some reason, `OVERSUBSCRIPTION` was set to 2 instead of 128. It still worked since we round up (~600/128=5) which gave us 40 bits of headroom. Sorry for the inconvenience and confusion caused by this.

2021-04-13 08:42 UTC, JanBobolz commented on src/main/java/org/cryptimeleon/craco/prf/zn/HashThenPrfToZn.java
> +                (p.bitLength() + aesKeyLength + OVERSUBSCRIPTION + 1) / aesKeyLength  // Compute number of AES instances required to get desired output bit length
If in your example, the good interval has size 2^255 and your 2x-AES outputs numbers from a size 2^256 interval, would that not mean that the probability of landing in the good interval would be 2^255/2^256  = 1/2 ?

2021-04-13 09:09 UTC, this-kramer commented on src/main/java/org/cryptimeleon/craco/prf/zn/HashThenPrfToZn.java
> +                (p.bitLength() + aesKeyLength + OVERSUBSCRIPTION + 1) / aesKeyLength  // Compute number of AES instances required to get desired output bit length
If that was the case, yes. But the bad interval is at most p.bitLength. Furthermore, using OVERSUBSCRIPTION=128, we guarantee that the good interval is at least 2^128 times larger than the bad interval

2021-04-13 15:18 UTC, this-kramer commented
Updated the describtion and changed some wrapper signatures for more flexibility

2021-04-13 15:26 UTC, JanBobolz commented on src/main/java/org/cryptimeleon/craco/prf/zn/HashThenPrfToZn.java
> +                (p.bitLength() + aesKeyLength + OVERSUBSCRIPTION + 1) / aesKeyLength  // Compute number of AES instances required to get desired output bit length
Okay, I just can't do divison, apparently :D nevermind

2021-04-14 08:45 UTC, JanBobolz requested changes
Please address my two comments. Otherwise, I'm fine with this. Good work! :)

2021-04-14 08:45 UTC, JanBobolz commented on src/main/java/org/cryptimeleon/craco/prf/zn/HashThenPrfToZn.java
> +    private BigInteger maxQuotient; // k from the description
"x [not k] from the Javadoc of this class"

2021-04-14 08:45 UTC, JanBobolz commented on src/main/java/org/cryptimeleon/craco/prf/zn/HashThenPrfToZn.java
> +    public Vector<Zn.ZnElement> hashThenPrfToZnVector(PrfKey prfKey, UniqueByteRepresentable hashInput, int vectorSize, String prefix) {
Please return RingElementVector for this to stay within our library stuff. 
We don't use `java.util.Vector` in the math library.

2021-04-14 11:13 UTC, this-kramer commented on src/main/java/org/cryptimeleon/craco/prf/zn/HashThenPrfToZn.java
> +    private BigInteger maxQuotient; // k from the description
Fixed

2021-04-14 11:17 UTC, this-kramer commented on src/main/java/org/cryptimeleon/craco/prf/zn/HashThenPrfToZn.java
> +    public Vector<Zn.ZnElement> hashThenPrfToZnVector(PrfKey prfKey, UniqueByteRepresentable hashInput, int vectorSize, String prefix) {
Okay, should I change Zn to Ring and Zn.ZnElement to RingElement then?

2021-04-14 11:22 UTC, JanBobolz commented on src/main/java/org/cryptimeleon/craco/prf/zn/HashThenPrfToZn.java
> +    public Vector<Zn.ZnElement> hashThenPrfToZnVector(PrfKey prfKey, UniqueByteRepresentable hashInput, int vectorSize, String prefix) {
Zn stays Zn (because your algorithm requires the specific Zn structure and won't necessarily work with other rings). Also ZnElement should stay this way. 
The only change I want is `Vector<ZnElement>` becomes `RingElementVector`.

2021-04-14 11:37 UTC, this-kramer commented on src/main/java/org/cryptimeleon/craco/prf/zn/HashThenPrfToZn.java
> +    public Vector<Zn.ZnElement> hashThenPrfToZnVector(PrfKey prfKey, UniqueByteRepresentable hashInput, int vectorSize, String prefix) {
That's a point. Changed the method signatures and adapted the tests

2021-04-14 12:09 UTC, JanBobolz approved these changes
Looks good

2021-04-14 12:30 UTC, merged